# Generated by Django 3.2.9 on 2021-12-14 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_schedule',
            name='period',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 15, 54, 5, 753826)),
        ),
    ]
